CREATE TABLE churches
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    address      VARCHAR(512),
    contact_info VARCHAR(255)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE app_user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(255) UNIQUE NOT NULL,
    password  VARCHAR(255)        NOT NULL,
    enabled   BOOLEAN             NOT NULL,
    role_id   BIGINT              NOT NULL,
    church_id BIGINT,
    FOREIGN KEY (role_id) REFERENCES roles (id),
    FOREIGN KEY (church_id) REFERENCES churches (id)
);


CREATE TABLE permissions
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE role_permissions
(
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles (id),
    FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE groups
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255) NOT NULL,
    description      TEXT,
    schedule         VARCHAR(255),
    location         VARCHAR(255),
    address          VARCHAR(512),
    contact_info     VARCHAR(255),
    gender           VARCHAR(50),
    age              VARCHAR(100),
    frequency        VARCHAR(50),
    group_leaders_id BIGINT,
    group_members_id BIGINT,
    FOREIGN KEY (group_leaders_id) REFERENCES app_user (id),
    FOREIGN KEY (group_members_id) REFERENCES app_user (id)
);

CREATE TABLE group_leaders
(
    group_id  BIGINT NOT NULL,
    leader_id BIGINT NOT NULL,
    FOREIGN KEY (leader_id) REFERENCES app_user (id),
    FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE group_members
(
    group_id  BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    FOREIGN KEY (member_id) REFERENCES app_user (id),
    FOREIGN KEY (group_id) REFERENCES groups (id)
);

CREATE TABLE category
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE group_categories
(
    group_id    BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id),
    FOREIGN KEY (category_id) REFERENCES category (id)
);



CREATE TABLE church_groups
(
    church_id BIGINT NOT NULL,
    group_id  BIGINT NOT NULL,
    FOREIGN KEY (church_id) REFERENCES churches (id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);
