


CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          username VARCHAR(50) UNIQUE NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          enabled BOOLEAN NOT NULL
);

CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE user_role (
                           user_id BIGINT NOT NULL,
                           role_id BIGINT NOT NULL,
                           FOREIGN KEY (user_id) REFERENCES app_user(id),
                           FOREIGN KEY (role_id) REFERENCES role(id)
);


CREATE TABLE groups
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    schedule     VARCHAR(255),
    location     VARCHAR(255),
    address      VARCHAR(512),
    contact_info VARCHAR(255),
    gender       VARCHAR(50),
    age          VARCHAR(100),
    frequency    VARCHAR(50)
);

CREATE TABLE group_leaders (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name        VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255) NOT NULL,
    group_id    BIGINT NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE TABLE group_categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id    BIGINT NOT NULL,
    group_category VARCHAR(255) NOT NULL,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);
