CREATE TABLE IF NOT EXISTS churches
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    address      VARCHAR(512),
    contact_info VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS roles
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS app_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255)        NOT NULL,
    enabled  BOOLEAN             NOT NULL DEFAULT TRUE,
    role_id  SMALLINT            NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS members
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name   VARCHAR(255),
    last_name    VARCHAR(255),
    email        VARCHAR(255) UNIQUE,
    home_phone   VARCHAR(20),
    mobile_phone VARCHAR(20),
    church_id    BIGINT,
    app_user_id  BIGINT UNIQUE,
    FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE SET NULL,
    FOREIGN KEY (church_id) REFERENCES churches (id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS permissions
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS role_permissions
(
    role_id       SMALLINT NOT NULL,
    permission_id SMALLINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
    FOREIGN KEY (permission_id) REFERENCES permissions (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ages
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(17) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genders
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(15) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS groups
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        VARCHAR(255) NOT NULL,
    description  TEXT,
    schedule     VARCHAR(255),
    location     VARCHAR(255),
    address      VARCHAR(512),
    frequency    TEXT,
    gender_id    SMALLINT,
    church_id    BIGINT,
    FOREIGN KEY (church_id) REFERENCES churches (id) ON DELETE CASCADE,
    FOREIGN KEY (gender_id) REFERENCES genders (id)
);

CREATE TABLE IF NOT EXISTS group_ages
(
    group_id BIGINT   NOT NULL,
    age_id   SMALLINT NOT NULL,
    PRIMARY KEY (group_id, age_id),
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE,
    FOREIGN KEY (age_id) REFERENCES ages (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_group_ages_age ON group_ages (age_id);

CREATE TABLE IF NOT EXISTS group_leaders
(
    group_id  BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, member_id),
    FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_group_leaders_member ON group_leaders (member_id);

CREATE TABLE IF NOT EXISTS group_members
(
    group_id  BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    PRIMARY KEY (group_id, member_id),
    FOREIGN KEY (member_id) REFERENCES members (id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_group_members_member ON group_members (member_id);

CREATE TABLE IF NOT EXISTS category
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS group_categories
(
    group_id    BIGINT   NOT NULL,
    category_id SMALLINT NOT NULL,
    PRIMARY KEY (group_id, category_id),
    FOREIGN KEY (group_id) REFERENCES groups (id),
    FOREIGN KEY (category_id) REFERENCES category (id)
);
CREATE INDEX IF NOT EXISTS idx_group_categories_category ON group_categories (category_id);
